### ISSUE TITLE
Question about Block or Shared File

### ISSUE THREAD

**Issue by wattsteve** [quobyte/docker-volume#1]
Does this volume plugin enable you to create a File on Block Volume (Network Disk) for use with a Database (like a Cinder use case) or does it enable you to create a Shared File Volume (like Manila / NFS) ?

**Comment by quolix** [comment]
Quobyte's main interface are shared file system volumes, thus the latter. With the plug-in you can map on file system into containers on several hosts.

**Comment by wattsteve** [comment]
Thanks!
