### ISSUE TITLE
Frequently fails create/mount

### ISSUE THREAD

**Issue by LLParse** [quobyte/docker-volume#21]
In testing this plugin, I often times see failed create/mount calls, and errors from the daemon that a container's volume is not mounted. I think we can remedy this with a few changes:

1. Create() should be idempotent - if Docker asks Quobyte to create a volume that already exists, return success.
2. Mount/Unmount are essentially no-ops, so we have to be creative. The Mount() FS directory check frequently fails because the mount hasn't yet propagated. This has bad consequences. I would recommend putting the FS check in a loop and waiting for up to N seconds (something reasonable) for the mount to propagate before returning failure.
3. From experience, the mount/unmount calls have to be very, very fast because a global lock is held which renders the daemon unresponsive to certain requests like `docker ps` for the duration of the call. Therefore, the loop in Mount() will cause performance problems, so I'd recommend moving it into the create phase immediately after the Quobyte API call.
4. Log all errors in the plugin - it isn't obvious why a Create() would be attempted 3x - logging the error will make debugging much easier.

**Comment by johscheuer** [comment]
Thanks for your feedback! I will try to find some time to fix these!

**Comment by johscheuer** [comment]
Hi @LLParse, did you encounter any further issues? 

I close this issue but feel free to reopen it :)
