### ISSUE TITLE
Failing on folder creation when it already exists

### ISSUE THREAD

**Issue by eduardolundgren** [quobyte/docker-volume#29]
In this example note two volumes, one "local" and the other "quobyte".

ubuntu@ip-172-16-0-214:~$ docker volume ls
DRIVER              VOLUME NAME
quobyte             db
local               db1

1. The "quobyte" volume rejects the container complaining the folder already exists.
> ubuntu@ip-172-16-0-214:~$ sudo docker run --env MYSQL_ROOT_PASSWORD=password -v db:/var/lib/mysql mysql:5.7
> mkdir: cannot create directory '/var/lib/mysql/': File exists

2. The "local" driver works fine.
> ubuntu@ip-172-16-0-214:~$ sudo docker run --env MYSQL_ROOT_PASSWORD=password -v db1:/var/lib/mysql mysql:5.7
> 2018-02-14T00:02:50.262876Z 0 [Note] mysqld (mysqld 5.7.21) starting as process 1 ...

**Comment by casusbelli** [comment]
Hi Eduardo!
I was unable to reproduce this so far, could you please provide some more input for us?:
- What Quobyte client (container) and docker versions are installed on the host (and are you using a local Quobyte client or the client container)?
- What is the content of /etc/fuse.conf on the host (if that file exists)
- What is the output of 'mount | grep quobyte' ?

**Comment by eduardolundgren** [comment]
Sure, sorry about not providing enough information.

Ubuntu 16.04.3 LTS (xenial)
Quobyte Server 2.0.0-pre7
Quobyte Client 2.0~pre7 (running as service, not container)
Quobyte Docker Client v1.3.1
Docker version 17.09.0-ce, build afdb6d4

---

Fuse Configuration

```
ubuntu@ip-172-16-0-93:~$ cat /etc/fuse.conf
# /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)

# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#mount_max = 1000

# Allow non-root users to specify the allow_other or allow_root mount options.
#user_allow_other
```

---

Mount

```
ubuntu@ip-172-16-0-93:~$ mount | grep quobyte
quobyte@quobyte.private-wedeploy-dev:7861 on /mnt/nfs type fuse.quobyte (rw,nosuid,nodev,noatime,user_id=0,group_id=0)
```

---

Volume Configuration

```
security_configuration {
  user_and_group_mapping_policy: USE_NUMERIC_ID_FOR_UNKNOWN
  windows_create_mode: 384
  windows_directory_mode: 448
  windows_group_selection: USERNAME
}
```

**Comment by casusbelli** [comment]
Please uncomment #user_allow_other in /etc/fuse.conf and retry

**Comment by eduardolundgren** [comment]
It works. Thank you for the help.

**Comment by casusbelli** [comment]
Welcome!
I'm just wondering, were there edits to the /etc/fuse.conf file?
Normally this option should be set by the package installation scripts. If there were no edits to the file we need to check out the packaging to prevent this from happening...

**Comment by eduardolundgren** [comment]
@casusbelli the installation was done manually and we've missed this step.
